name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # ou ta branche principale

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      with:
        # Le dossier racine contient directement ton index.html
        # Si ton site est dans un sous-dossier, spécifie-le ici
        # default is root, donc pas besoin de préciser si index.html à la racine
        # folder: './'  # optionnel ici
